from PyQt6 import QtCore, QtGui

MAIN_WINDOW_SIZE = QtCore.QSize(700, 880)
CALENDAR_WIDGET_GEOMETRY = QtCore.QRect(0, 0, 700, 400)
ADD_CALENDAR_EVENT_BUTTON_GEOMETRY = QtCore.QRect(20, 420, 660, 60)
SCROLL_AREA_GEOMETRY = QtCore.QRect(20, 500, 660, 360)
CALENDAR_EVENT_BUTTON_SIZE = QtCore.QSize(620, 48)

ADD_CALENDAR_EVENT_BUTTON_FONT = QtGui.QFont("Segoe UI", 20, 50)
CALENDAR_EVENT_BUTTON_FONT = QtGui.QFont("Segoe UI", 16, 50)

CALENDAR_EVENT_BUTTON_STYLE = "QPushButton { text-align: left; }"
